services:
  nginx:
    image: nginx:alpine
    container_name: cr-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker-files/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: cr-mariadb
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: cr-backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
