# docker-compose.backend.yml
services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: cr-backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true
