name: Deploy Spring Boot Project

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy build artifacts
        run: |
          JAR_FILE=$(ls build/libs/*.jar | sort -r | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no -r $JAR_FILE ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/anhye0n/web/tutorial_sejong/backend/

      - name: Restart backend service
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/anhye0n/web/tutorial_sejong/backend/
            git submodule update --init --recursive
            CURRENT_PID=\$(lsof -t -i:8080)
            if [ -n "\$CURRENT_PID" ]; then
              echo "Stopping process using port 8080 with PID \$CURRENT_PID"
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S kill -9 \$CURRENT_PID
            fi
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl restart tutorial_sejong_backend
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl status tutorial_sejong_backend
          EOF
